### ISSUE TITLE
1st Release - Rebranding Only

### ISSUE THREAD

**Issue by waywardgeek** [CipherShed/CipherShed#3]
There are a _lot_ of sub-tasks, so please help flesh this out.  We can create sub-issues for each of them.  I'm busy with work at the moment but in the morning I can do some of this:
- Someone should sign current master HEAD commit, after verifying original hashes and untared files match.
- Each developer must sign all commits going forward
- Recompile for each platform, and write Build Instructions:
  - Linux - ??? (??? = volunteer(s))
  - Mac - ???
  - Windows - ???
- Verify binaries match 7.1a (other than certificats)
  - This is a critical step which we cannot easily do after rebranding
- Rebranding:
  - 10 images need all new art - ???
  - Professional touch-up of artwork - Bill will send to graphic artist
  - Replace all instances of TrueCrypt w/CipherShed, including case variants
  - Download TrueCrypt Users Guide and rename TrueCrypt to CipherShed
- Manually verify all rebranding changes:
  - ANY code changes (zero?) should be verified by each core developers
  - Create hashes of binaries.
  - Recreate exact binaries by recompiling for each platform
  - Each dev verifying changes are OK should sign the binary hashes
- Prepare download site capable of handling the traffic
- Ship!

**Comment by waywardgeek** [comment]
Hi, guys.  I've moved to California, unpacked all the boxes (literally
weeks of effort), and joined Google in the user authentication team.
I still have to take an "open source" course tomorrow, but I finally
feel like I can have a few hours to contribute each week again.  So
long as they have no problem with my taking part in CipherShed, I hope
to be back starting this week.

Thanks,
Bill

**Comment by MrSchism** [comment]
Welcome back and congrats on the new gig!
