### ISSUE TITLE
Hardcoded Build date in About windows

### ISSUE THREAD

**Issue by geosone** [CipherShed/CipherShed#36]

**Comment by srguglielmo** [comment]
Can you include a screenshot? Or even better, find the line in the file that has it hardcoded.

Are you referring to the Help->About window? Where it says "Released by foo on February 7, 2012"?

**Comment by geosone** [comment]
yes i am revering to exactly this

**Comment by pdinc-oss** [comment]
Thanks.

moved to https://issues.ciphershed.org/issues/74
