### ISSUE TITLE
Turcrypt icon showing in taskbar

### ISSUE THREAD

**Issue by mewoch** [CipherShed/CipherShed#37]
this is with 0d6a45a on Mint 17.

I'm noting that in keeping with the roadmap most of the other Truecrypt related icon have gone, but noticed one lurking on my taskbar-equivalent.

![image](https://cloud.githubusercontent.com/assets/6393903/5593582/aeb1a728-9252-11e4-8700-831a16ba7f99.png)

**Comment by pdinc-oss** [comment]
good to know, thanks.

moved to https://issues.ciphershed.org/issues/73
