### ISSUE TITLE
Ubuntu repository 

### ISSUE THREAD

**Issue by arekbulski** [CipherShed/CipherShed#43]
It would be very convenient if you could install CipherShed on Ubuntu using the usual way things are installed, like below. I could also mention that ```cryptsetup``` that is used for managing LUKS volumes also allows to handle TrueCrypt volumes. I do not know if CS volumes are compatible or not, just mentioned.
```
$ sudo apt-get install ciphershed
```

**Comment by srguglielmo** [comment]
The project isn't yet at the stage where we can include it in package repositories. When there's an official release, we will definitely put effort into packaging it for as any distros/OSs as possible.

In addition, the TrueCrypt license (which CipherShed is required to use until the code is entirely rewritten) isn't compatible with free software guidelines. It would have to be in the "non-free" repo.
