### ISSUE TITLE
Official 0.7.4.0 release on github?

### ISSUE THREAD

**Issue by jonathancross** [CipherShed/CipherShed#45]
The 0.7.4.0 release is based on this git commit:
https://github.com/CipherShed/CipherShed/tree/be4dc698ffdc8d4414dbde838c2ddc7143c9dac2

Would be great to have an actual GitHub "release" created to remove any ambiguity:
https://github.com/CipherShed/CipherShed/releases

**Comment by GigabyteProductions** [comment]
Yeah. I do want to tag it but wanted to check with the others first before just pushing an irreversible tag to everyone.

**Comment by GigabyteProductions** [comment]
I've tagged the release. https://github.com/CipherShed/CipherShed/releases/tag/tags%2Fv0.7.4.0

**Comment by jonathancross** [comment]
Thanks!
