### ISSUE TITLE
gcc5.x -> cpp11 ABI -> Invalid characters encountered

### ISSUE THREAD

**Issue by gierdo** [CipherShed/CipherShed#47]
Hi!

If CipherShed is built on systems with gcc5.x, e.g. in my case Ubuntu 15.10, containers cannot be opened with the error message "Invalid characters encountered".

The Problem can be solved by building CipherShed with -D_GLIBCXX_USE_CXX11_ABI=0 and statically linking with wxwidgets.

In the makefile:
C_CXX_FLAGS := -MMD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -I$(BASE_DIR) -I$(BASE_DIR)/Crypto -D_GLIBCXX_USE_CXX11_ABI=0
.
.
.
WXCONFIG_CXXFLAGS : = -D_GLIBCXX_USE_CXX11_ABI=0

I ran into a cyclic dependency issue which had to be resolved with a linking group:
export LFLAGS := -Wl,--start-group  -lX11 -Wl,--end-group

**Comment by GigabyteProductions** [comment]
Hmmm... Could it be your environment? I'm not hitting circular dependencies nor am I needing static WX while testing this flag.

**Comment by gierdo** [comment]
I assumed that if built without cpp11 support, CipherShed had to be linked against wxwidgets without cpp11 support. It didn't even cross my mind that this was not necessary..

You are absolutely right, though. It works well and does not run into circular dependencies without static WX.

**Comment by GigabyteProductions** [comment]
Addressed in b4de5062848848b21be24a35c3c8dbe8bca3a401.
